#ifndef GRAPHICS_H
#define GRAPHICS_H

/* clear_entity: Clears 'entity' from the screen.
 */
void clear_entity(game_data *game, SDL_Rect entity);

/* draw_level: Draws level generated by 'generate_level()'.
 */
void draw_level(game_data *game);

/* draw_text: Draws 'text' on 'screen' surface with offsets 'pos_x' and
 *            'pos_y' on the X and Y axis, respectively. Check the README
 *            file for documentation on how the font file is formatted.
 */
void draw_text(game_data *game, const char *text, int pos_x, int pos_y);

/* load_font: Load font image file which is used for text rendering throughout
 *            the game.
 */
void load_font(game_data *game);

/* load_image: Loads an image pointed to by 'filename', optimises it and
 *             returns a pointer to the resulting optimized image surface.
 */
SDL_Surface *load_image(const char *filename);

/* update_text: Updates and redraws text on the screen.
 */
void update_text(game_data *game);

/* update_screen: Updates and redraws screen.
 */
void update_screen(game_data *game);

#endif
